<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-09-26T10:08:19 IST" name="Suite" finished-at="2022-09-26T10:08:42 IST" duration-ms="23687">
    <groups>
    </groups>
    <test started-at="2022-09-26T10:08:19 IST" name="Test" finished-at="2022-09-26T10:08:42 IST" duration-ms="23687">
      <class name="com.assesment1.Vagrant">
        <test-method is-config="true" signature="launchDriver()[pri:0, instance:com.assesment1.Vagrant@1a942c18]" started-at="2022-09-26T10:08:16 IST" name="launchDriver" finished-at="2022-09-26T10:08:19 IST" duration-ms="2717" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchDriver -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:com.assesment1.Vagrant@1a942c18]" started-at="2022-09-26T10:08:19 IST" name="launchApp" finished-at="2022-09-26T10:08:22 IST" duration-ms="3355" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="checkPushpa()[pri:0, instance:com.assesment1.Vagrant@1a942c18]" started-at="2022-09-26T10:08:22 IST" name="checkPushpa" finished-at="2022-09-26T10:08:39 IST" duration-ms="16810" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkPushpa -->
        <test-method signature="checkWiki()[pri:1, instance:com.assesment1.Vagrant@1a942c18]" started-at="2022-09-26T10:08:39 IST" name="checkWiki" finished-at="2022-09-26T10:08:40 IST" duration-ms="1266" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [January 7, 2022 (United States)] but found [17 December 2021]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [January 7, 2022 (United States)] but found [17 December 2021]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at com.assesment1.Vagrant.checkWiki(Vagrant.java:72)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:806)
at org.testng.TestRunner.run(TestRunner.java:601)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:433)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:427)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:387)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkWiki -->
      </class> <!-- com.assesment1.Vagrant -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
